In [2]:
import numpy as np

# Let's assume we have some data
data = np.array([
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],  # positive example
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],  # negative example
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],  # negative example
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],  # negative example
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],  # negative example
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],  # negative example
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],  # negative example
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],  # negative example
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # negative example
])

# We know that the positive class is the one where the 4th element is 1
positive_class = np.array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

# We want to sample some negative examples
num_negative_samples = 3

# We create a mask that gives us the negative examples
negative_mask = (data != positive_class).any(axis=1)

# We use this mask to get the negative examples
negative_examples = data[negative_mask]

# We randomly sample from the negative examples
negative_samples = negative_examples[np.random.choice(negative_examples.shape[0], num_negative_samples, replace=False)]

print(negative_samples)


[[0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 0]]


In [9]:

negative_examples


array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])